# Setup
title:        🥰
tagline:      성경읽기표 소개 페이지
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Author name
  url:        http://eunjin3786.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
